### ISSUE TITLE
Creative Menu

### ISSUE THREAD

**Issue by Fortist** [cyanobacterium/BaseMetals#15]
This needs its own Creative tab, or at least put it with the rest of your mods.

**Comment by DrPlantabyte** [comment]
How should the creative tabs be organized? What do you think is most convenient for the majority of users?

For example, I could have a single tab for all Base Metal items, but that might be inconvenient if you are looking for tool items; or I could add three tabs for tools, ingots, and blocks, but laving lots of tabs from each mod can get really annoying in creative mode; or I could leave the tools, weapons, and armors in the vanilla tabs (making them easy to find in creative mode) but add a tab for all other Base Metals.

**Comment by Fortist** [comment]
Your blocks, tools and other items in its own, one, tab. You can keep it separate from the Advantage stuff.

**Comment by DrPlantabyte** [comment]
You seem very certain that 1 tab is the way to go, but I'm still thinking about it. I'll ask the MinecraftForum.net crowd to weigh in.

**Comment by DrPlantabyte** [comment]
New update (v1.6.2) has a Base Metals creative tab with sorted items and a search bar. You're welcome.
