### ISSUE TITLE
BaseMetals + k4lib crash on startup

### ISSUE THREAD

**Issue by LlubNek** [cyanobacterium/BaseMetals#16]
k4lib (required by HydCraft) crashes on client start when BaseMetals is installed.

Here are the crash reports:
https://pastee.org/j3q5u
http://pastebin.com/zBznvtms

Here's a log:
http://pastebin.com/gDUM0ZJG

And here's the k4lib issue:
https://github.com/K-4U/Hydraulicraft/issues/180

I'm using BaseMetals-1.6.1.jar and k4lib-1.8.9-1.0.8-universal.jar

**Comment by DrPlantabyte** [comment]
Found the bug in Hydraulicraft source code, as described in K-4U/Hydraulicraft#180
