### ISSUE TITLE
internal server/server crash on world creation

### ISSUE THREAD

**Issue by Sailren** [cyanobacterium/BaseMetals#17]
used verison is basemetals{1.6.1} [Base Metals](BaseMetals-1.6.1.jar)

crash report can be found here: http://paste.ubuntu.com/14828214/

**Comment by DrPlantabyte** [comment]
Could I see the contents of the files in **config/orespawn** please? I think they may be at fault.

**Comment by Sailren** [comment]
http://paste.ubuntu.com/14834500/

http://paste.ubuntu.com/14834506/

is it conflicting with substratum?

**Comment by DrPlantabyte** [comment]
Ok, thanks for the orespawn files. That helped me find a bug. I'll publish an update soon, but in the mean-time, you can prevent this crash by editing the minecraft.json orespawn file and increasing the emerald variation from 0 to 1.
