### ISSUE TITLE
Conflict with Biomes-O-Plenty

### ISSUE THREAD

**Issue by JoeSchmo2840** [cyanobacterium/BaseMetals#18]
I am not sure whats going on here, so I am submitting this issue to both mods:

http://pastebin.com/3yg5nnUc

**Comment by JoeSchmo2840** [comment]
NVM this is a sponge error. Very sorry

**Comment by DrPlantabyte** [comment]
This is a bug in Base Metals accidentally introduced in version 1.6.3 and will be fixed soon.
