### ISSUE TITLE
lead and copper ingots compatibility

### ISSUE THREAD

**Issue by AngelCry** [cyanobacterium/BaseMetals#20]
sorry if issue come not from this mod, i just not so experienced to find it by my self. i have few mods already in MC 1.8.9 and now decided add all Advantage-s + Base Metals. on first load i got warning about lead and copper ingots:

```
[10:16:42] [Server thread/ERROR] [FML/]: There are unidentified mappings in this world - we are going to attempt to process anyway
[10:16:42] [Server thread/ERROR] [FML/]: Unidentified item: hydcraft:ingotCopper, id 5085
[10:16:42] [Server thread/ERROR] [FML/]: Unidentified item: hydcraft:ingotLead, id 5087
```

i seen many times as different mods **adds** their own metals, but is first time when i see as some metals get **removed** after adding new mod. i only can guess if some mod do not use ore dictionary (or use it in some wrong way) because from times, when oreDict been introduced such conflicts are gone. those ingots been from HydrauliCraft and i use HydCraft-1.8.9-3.1.64, BaseMetals-1.7.0, Forge 1724. 
also, can be related, as i add your mods to existing world, i decided to use retrogen, so i add cyano.basemetals.worldgen.OreSpawner into simpleretrogen config (at same time i think is unlikely, because retrogen used to work with ores and will not touch ingots). anyway, i use simpleretrogen-1.8.9-2.2.2+3.
another thing, which looks weird - copper and lead ingots dont have texture. usually i not wonder about such things in mods for MC 1.8.9, because most of them still unfinished, but i checked assets in base metals jar and found textures for both ingots, so i wonder why they not applied.
thanks in advance :D

**Comment by DrPlantabyte** [comment]
There was a bug in Hydraulicraft related to these two metals and I'm not sure if it has been completely fixed yet in that version of Hydaulicraft: https://github.com/K-4U/Hydraulicraft/issues/180

Base Metals lead and copper ingots are definitely textured properly without Hydraulicraft installed and Base Metals uses the OreDictionary correctly (and other mods, such as OpenComputers and Iron Chests have no trouble with Base Metals ingots), so this is a Hydraulicraft bug.

**Comment by AngelCry** [comment]
thanks for answer. want to note though, i still feel is weird about textures, because considering JEI is base metals ingots (to be more clear - i just looked in JEI what can be done with lead ore and smelting recipe show placeholder for ingot. and you may know, JEI also shows mod name from which item come). another note - Hydraulicraft  have texture for lead ingot as well. so, both mods have textures, but none are applied at the end -_-
