### ISSUE TITLE
Crashes on start with Forge 1809

### ISSUE THREAD

**Issue by kwpugh** [cyanobacterium/BaseMetals#22]
Crash report:  http://pastebin.com/raw/r3QfuxiK

**Comment by DrPlantabyte** [comment]
I'm unable to see your pastebin. Is there a typo in the URL?

Also, I'm not having trouble with Forge build 1804, so it could be a bug in 1809. Either downgrade Forge or wait for a newer version and let me know if the bug persists.

**Comment by kwpugh** [comment]
I'm waiting at 1804

**Comment by TrikSteve** [comment]
On Forge 1813 and still crashing even with a clean 1.9 with just forge.  http://pastebin.com/CCquRDUa

**Comment by DrPlantabyte** [comment]
Fixed in version 2.0.3
https://github.com/cyanobacterium/BaseMetals/releases/tag/v2.0.3
