### ISSUE TITLE
Crash during modloading [forge 1811][version 2.0.2]

### ISSUE THREAD

**Issue by Mythrrinthael** [cyanobacterium/BaseMetals#23]
[Here](http://pastebin.com/e8KbK74p)'s the bug report. Seems to be related to the universal bucket.

**Comment by kreezxil** [comment]
Confirmed!

Issue: base-metals-1.9-2.0.2 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/4c059d1132c846ef91b8

fml server latest:
https://gist.github.com/8ab0c8c81be2e4da3eee

**Comment by kreezxil** [comment]
I thought I might try rolling back to 1.9-2.0.1 but it didn't help, still crashed in 1811.

Issue: base-metals-1.9-2.0.1 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/adf63fcf0cc45f7e6b9f

fml server latest:
https://gist.github.com/c19e9808d876194a418d

**Comment by LlubNek** [comment]
Here's another:
http://pastebin.com/REByHGB8
http://pastebin.com/ddnen747

Also 2.0.2 on 1811.
Might be related to NeoTech since it's also marked errored during Preinit.

**Comment by ArMoReDfUrY** [comment]
it's all Forge related, they changed a lot of code.
a ton of calls need to be re-written/spell corrected to the new calls.
the changes are both on Forge 1.8.9 - 11.15.1.1808+ and Forge 1.9 - 12.16.0.1805+ versions
its a ton of work. give em a few days. 
Forge 1.9 - 12.16.0.1811 would be the one to build on for 1.9.
Forge 1.8.9 - 11.15.1.1808 has the same changes. it's gonna be a long wait for the 1.8.9 mods to all update.

**Comment by DrPlantabyte** [comment]
I'll recompile later this week. Until then, use an older version of Forge (e.g. build 1804).

**Comment by kreezxil** [comment]
I love you man!!! I really do, unfortunately for those of us building mod packs, we can't roll back. 

-----Original Message-----

**Comment by DrPlantabyte** [comment]
Fixed in version 2.0.3
https://github.com/cyanobacterium/BaseMetals/releases/tag/v2.0.3
