### ISSUE TITLE
village/entities problem

### ISSUE THREAD

**Issue by ghost** [cyanobacterium/BaseMetals#24]
see: https://github.com/SpongePowered/SpongeForge/issues/590

**Comment by DrPlantabyte** [comment]
See if disabling villager trades fixes the issue.

**Comment by ghost** [comment]
when set in the config:

_B:enable_custom_villagers=false_

problem solved

**Comment by DrPlantabyte** [comment]
Thanks. That conclusively points to my Better Villagers entities as the problem, though I am still puzzled as to why it is a problem. The Better Villagers are identical to the normal villagers except for their functions related to generating new trades.

**Comment by ghost** [comment]
Something similar with villagers You repaired in this commit: https://github.com/cyanobacterium/BaseMetals/commit/47252d8adb23d9c46790d401505b86fdec0e7099

**Comment by DrPlantabyte** [comment]
There's a new version of Base Metals out, but I'm still working on this performance issue. Since there's nothing I can do any further with the Better Villagers as far as I can tell, I'll have to remove them entirely and use voodoo magic (aka java reflection) to manually edit the default Minecraft villager entities (something I really didn't want to do).

**Comment by ghost** [comment]
1.8.9 develop stopped? This issue is 1.8.9 related.

**Comment by DrPlantabyte** [comment]
Oh, I only get the frame-rate drop in Minecraft 1.9.0
Unless I can make it happen in 1.8.9, I can't work on fixing it because I won't know if I succeeded.

EDIT: When I fix it in 1.9.0, I'll apply the same fix to 1.8.9 and then you can tell me if that fixes the problem :)

**Comment by ghost** [comment]
ok, thanks!

**Comment by DrPlantabyte** [comment]
Better Villagers removed in versions [2.1.0](https://github.com/cyanobacterium/BaseMetals/releases/tag/v2.1.0) and [1.8.0](https://github.com/cyanobacterium/BaseMetals/releases/tag/v1.8.0) (replaced with array hacking)
