### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KristjanKr** [cyanobacterium/BaseMetals#25]
Crashing on start-up!
http://paste.ee/p/6kDUU
Base metals: BaseMetals_1.9-2.1.0
Forge: 1826

**Comment by Radiant-Xyz** [comment]
Crashes here too. Forge 1826 with only BaseMetals installed.

**Comment by DrPlantabyte** [comment]
Yup, there was another refactor in the Forge API and all mods need to recompile (again!). New version about to go live (v2.1.1) compiled for Forge build 1832. I would not be surprised if it crashes when used with Forge build 1833 or 1831 (such is the state of Forge at the moment)
