### ISSUE TITLE
Add new materials

### ISSUE THREAD

**Issue by jriwanek** [cyanobacterium/BaseMetals#26]
Aluminum
Cupronickel (alloy)
Titanium

Possibly Magnesium and Rutile (Raw Unprocessed Titanium)

If you want, I've got most all of the code done but I don't have any models for any of it yet, I can send a push for you to poke through if interested.

**Comment by DrPlantabyte** [comment]
I think an add-on mod would be more appropriate. Base Metals focuses on common metals without breaking the pre-modern atmosphere of Minecraft, though Cupronickel would be a good addition.

Aluminum and Titanium cannot be easily refined without electricity (especially aluminum), so these metals really symbolize the modern era. Thus I think a "Modern Metals" add-on would be a fantastic idea. It could also include osmium, tungsten, and uranium.

Alas I don't have the time to make such an add-on myself, but I'd be willing to lend a hand if you want to make it. If you write the code and make the textures, I'll provide all the the .json files you need.

**Comment by medsal15** [comment]
Suggestion: Make uranium radioactive and make lead protect you from radioactivity.

**Comment by jriwanek** [comment]
Well, I've got no problem at all making it an addon, as you've shown interest in cupronickel I'll send you a push later on with that (probably won't include textures initially), also, while I'm on it, are you interested in Rods, gears and nugget sized piles of dust for the main mod or should I look at doing those as an addon too?

**Comment by jriwanek** [comment]
Other suggestions for the list:

Platinum
Shears

Either of these interesting for the base mod or would you rather these go in an addon too?

**Comment by DrPlantabyte** [comment]
I think that Tinker's Construct has all the rods and tiny dust piles covered, so I'll pass on that. I added a shears recipe for steel, but I suppose one could make a version of shears for every metal.

I've been thinking of adding platinum but I just can't come up with a good use for it. Real-life usage of platinum is mostly for advanced chemistry and occasionally in art for people who want to show off how much money they have (I've seen pure platinum and honestly it looks exactly the same as polished silver). If there's a mod out there that uses platinum for something, then I'll add it to Base Metals.

**Comment by jriwanek** [comment]
I'm not sure about tconstruct and tiny dust piles (Will look later).

Pretty sure you're correct about rods however.

So, on further suggestions (Yes, I'm full of ideas), What about gears?

Once I've got ModernMetals to some point of functionality I can have a look into all of the above for you (Hey, I'm suggesting stuff, only fair I put my code where my mouth is after all), I may also look into Arrows, Crossbows and Crossbow Bolts too.

**Comment by DrPlantabyte** [comment]
I'm busy updating my other mods right now, so I'm not able to add anything to Base Metals for the next month. So here's some tips that will make it easier for you to try things out in your own code.

Tip 1: Download the Power Advantage project and use Netbeans to open the _MinecraftModUtils_ project in the _extras_ folder. Then run the file **FileDuplicateAndTextReplace.java** to select all of the .json files of a single metal from Base Metals and duplicate all of them for a new metal  (e.g. select all of the adamantine json model files, then type "adamantine" and "aluminum" in the text fields).

Tip 2: For new types of items, you can iterate over all of the metals in Base Metals by iterating over the **cyano.basemetals.init.Materials.getAllMetals()** collection (e.g. https://github.com/cyanobacterium/BaseMetals/blob/master/src/main/java/cyano/basemetals/init/Recipes.java#L96 )

**Comment by jriwanek** [comment]
Thanks muchly, with the amount of "new" stuff I'll be learning in this process, I reckon a month is gonna be a fair amount of time for me to get my head round it all.... and get some art into the mix so looks like it'll all come together nicely in the end. (:
