### ISSUE TITLE
1.9-2.0.3 crashes dedicated forge server 1.9 build 1863 on startup

### ISSUE THREAD

**Issue by kreezxil** [cyanobacterium/BaseMetals#27]
Issue: base-metals-1.9-2.0.3 crashes dedicated forge server 1.9 build 1863 on startup

crash report:
https://gist.github.com/78b804340077961b1e07f80baf673408

fml server latest:
https://gist.github.com/0810aecdbaf719ebfac54960f7d01775

**Comment by jriwanek** [comment]
BaseMetals 2.1.1 has been out since the 3rd of april, works just fine on forge 1863.

**Comment by kreezxil** [comment]
Hey! Thanks for that, I didn't see it on Curseforge where 2.0.3 is the latest version reported. I forgot to check here. :(

**Comment by jriwanek** [comment]
That's weird, on curseforge (right now) 2.1.1 _is_ the latest version reported, I guess it's possible your ISP is doing weird proxying on your connection though.

**Comment by kreezxil** [comment]
My bad, it's the gray hair and false teeth messing with me. I just looked at my Solder distro and there it was, 2.1.1, somehow I manage to forget to update to the 2.1.1.
