### ISSUE TITLE
Smelting in a Power Advantage furnace doesn't grant the Base Metals metal-type achievements

### ISSUE THREAD

**Issue by christate** [cyanobacterium/BaseMetals#28]
At least, this is the case with the steam-powered furnace in the SteamAdvantage co-mod.

I'm using Minecraft 1.9 with:

Forge 1.9-12.16.0.1863-1.9
BaseMetals_1.9-2.1.1

with

PowerAdvantage_1.9.0_2.0.2
SteamAdvantage_2.0.1

I suspect this might actually be something "wrong" with PowerAdvantage, since it also doesn't grant XP for smelts performed in the steam furnace.

**Comment by DrPlantabyte** [comment]
I forgot to invoke the achievement event bus in my machines. Next time I update those mods, the fix will be included.

EDIT: Wait, there is no achievement event bus. I don't know why the achievements don't work, but the lack of XP is a deliberate design choice (normal Minecraft furnaces don't give out XP either if connected to a hopper or other inventory machine).

**Comment by DrPlantabyte** [comment]
I discovered that there is a special furnace slot class for inventory slots that do furnace related achievement events. This issue will be fixed in Power Advantage 2.1.0 (and also the next Steam and Electric Advantage updates).
