### ISSUE TITLE
New Stuff

### ISSUE THREAD

**Issue by jriwanek** [cyanobacterium/BaseMetals#32]
I've begun working on Arrows, Bows, Bolts, Shears, and Small Piles
Checkout Modern Metals to have a play

Rationalization for all but the small piles is pretty obvious
Small Piles: Nugget size piles of dust.

Current Recipe Ideas:
https://github.com/jriwanek/ModernMetals/wiki/Recipes

If you have alternate preferences, let me know.
## **Current Status (In Progress)**

New Tool durability needs tweaks
Fishing Rods Don't work correctly
## **Current Status (Not yet started)**

Bows work but shoot normal arrows
Arrows and bolts currently interchangeable
No textures for Crossbows or Bolts
Traits (as Suggested in https://github.com/cyanobacterium/BaseMetals/issues/26#issuecomment-208015331): Not Implemented

Is there anything else you'd like to see in Base Metals?

**Comment by jriwanek** [comment]
Additional: Fishing Rods & Horse Armor

**Comment by DrPlantabyte** [comment]
Cool!

**Comment by jriwanek** [comment]
Could really use a suggestion on a recipe for crossbows still. (:

**Comment by jriwanek** [comment]
Recipes complete, JSON Files done (They might need to change however).

**Comment by DrPlantabyte** [comment]
I've been busy updating my final mod to MC 1.9 (Minecraft Mineralogy), but I give it a try when I get a chance.

**Comment by jriwanek** [comment]
_nods_ I'm pushing a limited test to curseforge shortly so that'll make it a bit easier to play with the basic stuff (new stuff listed above not included). No hurry, take your time. Oh, I took the liberty of assigning you as "mascot" on modern metals, if you'd prefer author or something else, let me know.

**Comment by DrPlantabyte** [comment]
That's fine with me.

I'm really looking forward to the crossbow. If it is any help, you can look at my code for the black-powder musket in Steam Advantage.

**Comment by jriwanek** [comment]
That's actually a really good idea I'd been trying to work out how to do the crossbow without just making it into another bow. (:

**Comment by jriwanek** [comment]
Updated initial comment: Moved long rambling recipe list to wiki.
