### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by jriwanek** [cyanobacterium/BaseMetals#33]
The green lines (which show up on the minecraft tab for the vanilla achievements) don't appear for the achievements page in base metals, I've had a look around but I've got no clue how to fix it however.

**Comment by DrPlantabyte** [comment]
They aren't appearing for any mod, as far as I can tell. I figure it is under development by the Forge team. If you find a mod that does show the lines, let me know and I'll ~~use black magic to steal their secrets~~ ask the mod author how they did it.

**Comment by jriwanek** [comment]
xD Will do.

**Comment by jriwanek** [comment]
It all magically works with current forge.
