### ISSUE TITLE
Possible new metals

### ISSUE THREAD

**Issue by jriwanek** [cyanobacterium/BaseMetals#35]
Need you to look over the other metals in modern metals to see if any would be suitable in base metals before I move MM to beta status: (I'm aware some of them are rather obviously no, but I like to be certain)

Cadmium
Chromium
Iridium
Magnesium
Manganese
Osmium
Plutonium
Tantalum
Tungsten
Uranium
Zirconium

I'm also looking into making the following non metals, possibly as part of MM, possibly as a seperate utility mod, any of interest to you (or the concept of a utility mod for them in general):

Lithium
Niter
Phosphorous
Saltpeter
Silicon
Sulfur

**Comment by DrPlantabyte** [comment]
I think those are all good for Modern Metals and that selection of non-metals pretty much covers all of the other tech mods that are our there. Looks good to me.

**Comment by jriwanek** [comment]
Alrighties, awesome, Got a feature request the other day for Stainless Steel

I also thought of:

Antimony
Bismuth
Pewter

Anyways, Looks like I'm almost ready to pop out a beta now.
