### ISSUE TITLE
classes

### ISSUE THREAD

**Issue by schuylernathaniel** [cyanobacterium/BaseMetals#36]
latest 1.9 release causes forge to crash citing that classes are incorrectly defined

**Comment by jriwanek** [comment]
Are you also using the latest version of forge? (1865), I am here and it appears to work fine for me, could you provide a crash report please?

**Comment by DrPlantabyte** [comment]
That error usually means that you are using java 7 or earlier (Base Metals requires java 8), but I'd need to see the full crash report to be sure.

**Comment by schuylernathaniel** [comment]
ah. thanks for letting me know that it needs java 8. i just made the switch to 1.9 from 1.8 and didn't think to update the java.

**Comment by jriwanek** [comment]
For reference, if you use the new minecraft launcher package it comes bundled with Java 8
