### ISSUE TITLE
Mod conflict with malisis's doors

### ISSUE THREAD

**Issue by b0bst3r** [cyanobacterium/BaseMetals#39]
If you have base metals and malisis's installed the vanilla wooden doors are textureless in hand, inventory and in JEI.  They place down fine in the world.

http://i.imgur.com/fpxMPjr.png

If you remove base metals the doors are present, if you remove malisis's doors the textures are present,  If I turn on the 3D setting in malisis's config the textures are present.

Forge 1865
BaseMetals_1.9-2.1.1
malisiscore-1.9-3.0.5
malisisdoors-1.9-4.0.1
jei_1.9-3.3.0.193

**Comment by jriwanek** [comment]
Confirmed, however the problem appears to be malisis' doors modifying vanilla code
Setting:
B:config.modifyVanillaDoors=false
Or:
B:config.use3DItems=true

causes vanilla doors to render with basemetals installed

I'll look into whether we can work with/around the changes they're making, I'm not however sure atm why base metals being installed causes the vanilla doors not to render with malisis installed.

**Comment by jriwanek** [comment]
Related notes:

http://pastebin.com/wfLECrqr

**Comment by DrPlantabyte** [comment]
Is Malisis incompatible with 3D texture packs?

**Comment by jriwanek** [comment]
Not a clue, Probably gonna have to bring it up with the author.

**Comment by jriwanek** [comment]
Moved to new tracker
