### ISSUE TITLE
Iron Crack Hammer doesn't work on blocks of coal

### ISSUE THREAD

**Issue by liftoff** [cyanobacterium/BaseMetals#4]
According to NEI I can use a crack hammer on blocks of coal to make 9 carbon dust.  This doesn't work...  It takes forever and the block of coal just ends up being destroyed.

**Comment by DrPlantabyte** [comment]
That's not good, I'll fix it next chance I get. Does it work if you drop a coal block on the floor and use the right-click method?

**Comment by DrPlantabyte** [comment]
This bug is now fixed in version 1.2.3. Thank you for bringing it to my attention.
