### ISSUE TITLE
Liquid of all metals?

### ISSUE THREAD

**Issue by zlyfire** [cyanobacterium/BaseMetals#41]
I'm playing in the 1.9 version. I was processing my ores in a Tinkers' smeltery when I realized multiple things:  
Some metals do not have a liquid form.  
Certain alloys weren't combining as they should.  
For instance, with the alloys, liquid brass does exist. However, it won't combine in the smeltery. It requires me to make dust of the metals, craft them into blends, smelt in a furnace, then I can melt the metal in the smeltery.  
My thought was that all metals could have a liquid form and that the alloys could have a liquid metal recipe. If this is already implemented and it's just a difference in how Tinkers' works in 1.9 or something, then I apologize.

**Comment by jriwanek** [comment]
Cuurrently you can melt down the ore blocks in the smeltery (not all of them as you cover) and you can melt ingots, nuggets and blocks (again as you cover, not all of them), I'm intending to add fluids for _all_ metals at some point though. There's minor issues with how the forge universal bucket is set up currently and I'm intending to fix that too so, It's all on my list.

Just give it time and it'll come.

**Comment by zlyfire** [comment]
Alright cool. Intending for liquid alloy recipes as well?

**Comment by jriwanek** [comment]
That's the plan.
