### ISSUE TITLE
BaseMetalsAPI crash (1.9)

### ISSUE THREAD

**Issue by synthetixa** [cyanobacterium/BaseMetals#43]
[PasteBin CrashLog](http://pastebin.com/exCHE0qZ)

Hello. I'm developing an atomic power mod using BaseMetals and PowerAdvantage. I am currently having a problem getting it to run.

My mod is only a skeleton and doesn't touch either of your mods yet. The crash log above is the output. It gets to the preinitialization phase then crashes. I couldn't find anything similar in your issue tracker, so I posted this. Thanks for any help!

**Comment by jriwanek** [comment]
Outdated mappings.

**Comment by synthetixa** [comment]
Yeah, it's fixed.
