### ISSUE TITLE
Air pockets with Modern Metals disabled

### ISSUE THREAD

**Issue by xenoflot** [cyanobacterium/BaseMetals#45]
Hi, I'm running "The New Frontier" 1.9 modpack which includes BaseMetals, ModernMetals and your Advantage mods. I have disabled ModernMetals and when I generate a new world, it's full of air pockets.

To troubleshoot, I disabled all mods and progressively re-added them. As soon as I re-added BaseMetals, the air pockets reappeared. With BM and MM both enabled, no air pockets.

Any idea why this is happening?

**Comment by jriwanek** [comment]
Modernmetals uses Basemetals orespawn if you look in .minecraft/config/orespawn you will find JSON files for it, if you remove Basemetals then the orespawn won't be occuring, if you're trying to disable just modernmetals, then you'll need to remove modernmetals.json from that dir.

**Comment by xenoflot** [comment]
That's great, thanks!
