### ISSUE TITLE
Any chance of a 1.9.4 version

### ISSUE THREAD

**Issue by b0bst3r** [cyanobacterium/BaseMetals#49]
Please, I can't update the pack and nearly all mods have moved onto 1.9.4

**Comment by jriwanek** [comment]
I'm working on it, don't worry.

**Comment by jriwanek** [comment]
@b0bst3r It's been released to curseforge a few moments ago, might take a little for it to sync but it should work.

**Comment by b0bst3r** [comment]
Thank you very much just 1 to go now and I can switch up :D
