### ISSUE TITLE
Spinning-Off Orespawn as its Own Library

### ISSUE THREAD

**Issue by DrPlantabyte** [cyanobacterium/BaseMetals#54]
JRIwanek and I decided to make the ore spawning its own stand-alone API library.

Here's the plan: For Minecraft 1.9.4 and later releases, Orespawn will be its own API, but earlier (legacy) versions will keep the API as part of Base Metals.

**Comment by jriwanek** [comment]
Works for me, I'm still working on bringing BM for 1.8.9 in line with the 1.9 release.

**Comment by DrPlantabyte** [comment]
Ore Spawn release done. I'll go ahead and remove it from the 1.9.4 version of Base Metals (and make a few bug fixes) and then push an official release for Base Metals 1.9.4

**Comment by jriwanek** [comment]
Sounds like a plan, I'll backport anything relevent to the older releases.

**Comment by DrPlantabyte** [comment]
Spin-off complete. Version 2.3.0 now depends on Ore Spawn instead of including it. You can disable the dependency in the config file (but then you'd have to manually specify the spawning of all ores using another mod or else there will be no Base Metals ores in your world).
