### ISSUE TITLE
(Suggestion) Ability to disable sections of the mod

### ISSUE THREAD

**Issue by oh-noey** [cyanobacterium/BaseMetals#55]
It would be nice to be able to completely disable items/sections of the mod, as in stopping them from even existing in the game. For example, there could be an option to disable each ore, and its subset items, entirely. Another use of this would be to completely disable the hammer, for those that want users to have to use a pulverizer type block from another mod.

**Comment by DrPlantabyte** [comment]
I'll see about adding an option to disable the recipes for crafting the crack hammers, but I won't remove any items from the game. The bugs and problems that will inevitably create is not worth it just to have a clean-looking creative tab. You can already disable unwanted metal ores from spawning in the world.

**Comment by ruyanve** [comment]
Would be great to disable the hammer.

**Comment by DrPlantabyte** [comment]
Hammers can be disabled in version 2.3.3
