### ISSUE TITLE
Feature Request: mining tier configuration file

### ISSUE THREAD

**Issue by Syndaryl** [cyanobacterium/BaseMetals#56]
Orespawn does a great job of letting a modpack author integrate added metals into worldgen - but I would like to be able to reorganize the material tiers in a JSON.

EG: require stone level tools to mine copper, require copper-level tools to mine iron, require iron level tools to mine tin, require bronze/steel level tools to mine diamond. Or whatever.

If you really want to go nutzo with configurability, put the armor and damage qualities in the JSON too.

Naturally the insane next level is building ores dynamically directly from the JSON (including a property with a path to the image) but that's probably taking things a bit too far :D

**Comment by jriwanek** [comment]
I might consider making another mod for doing custom ores later.

**Comment by DrPlantabyte** [comment]
The mining tool level, as well as tool use efficiency, effectiveness, damage, and armor protection are all derived from a single "hardness" property for that metal. Thus, without doing a drastic re-write, we cannot make copper ore require an iron pick-axe (or equivalent) without making copper tools equivalent to diamond tools.

**Comment by Syndaryl** [comment]
I was thinking the other way around:
Vanilla is wood->stone->iron->diamond
I'm trying to set it up for wood->stone->copper->iron(makes steel)->Diamond->obsidian/cold iron->adamant kinda thing.

**Comment by jriwanek** [comment]
With the way BM is currently set up that'd still require a lot of changes, I myself am certainly not against it, but it's @cyanobacterium's call in the end. (It's more than just changing the mining levels, would have to add more tiers in too)

**Comment by DrPlantabyte** [comment]
Changing how existing blocks/items in Minecraft work is difficult to do and difficult to maintain when Minecraft updates. Plus this feature will interface poorly with other mods. I will decline this feature request, but thank-you for your interest. :)
