### ISSUE TITLE
Going through my mods I crash with newest basemetals any help would be great 

### ISSUE THREAD

**Issue by lichking1981** [cyanobacterium/BaseMetals#59]
I used process of elimination to figure out which mod was crashing my minecraft and attaching crash report any help would be great. Love your mods
[crash-2016-06-11_15.12.33-client.txt](https://github.com/cyanobacterium/BaseMetals/files/310458/crash-2016-06-11_15.12.33-client.txt)

**Comment by jriwanek** [comment]
net.minecraftforge.fml.common.MissingModsException: Mod orespawn (DrCyano's Ore Spawn Mod) requires [1.0.0]

Try adding orespawn.

**Comment by lichking1981** [comment]
Adding the mod OreSpawn_1.9.4-1.0.3 fixed the problem thank you.
