### ISSUE TITLE
[request] Add minestrappolation 4 compatibility

### ISSUE THREAD

**Issue by medsal15** [cyanobacterium/BaseMetals#6]
Minestrappolation adds more ores with their crushed variants. I just want the hammers to be able to crush these ores. And same for the stones.

**Comment by DrPlantabyte** [comment]
I'll add the ability to add custom hammer recipes in the config files in the next update.

Thanks for the idea.

**Comment by DrPlantabyte** [comment]
New version (1.3.3) now allows you to add your own recipes. I could not find an API or source code for Minestrappolation, so you will have to manually generate the recipe list. If you do, please post it on the Base Metals forum for the benefit of others and so you can receive proper credit for your hard work.

**Comment by medsal15** [comment]
Thank you!
