### ISSUE TITLE
Durability, Mining Speed, new Recipe

### ISSUE THREAD

**Issue by ghost** [cyanobacterium/BaseMetals#60]
can you:
give same durability for same materials (example: pickaxe has different durabilitiy as the Crack Hammer).
change the mining speed for different materials for me it felt all materials have the same speed by ore mining.
add a Recipe for plates and shields (more durability).

**Comment by jriwanek** [comment]
Do you mean to combine plates with shields?

**Comment by ghost** [comment]
Yes. I use mods they don't using these Plates for crafting so i turn them off usualy. I thougth why not give them a use and make shield more durable (without changing the shield behavior per se)
Edit: I forgot an option  add Plates to shields like the Banners. (maybe looks nice)

**Comment by DrPlantabyte** [comment]
Crack Hammers deliberately have less durability than other tools of the same material for game balance reasons.

That's an interesting idea for shields. I'll put that on the to-do list.

**Comment by jriwanek** [comment]
Moved to new issue tracker.
