### ISSUE TITLE
All ores considerably harder than Iron

### ISSUE THREAD

**Issue by dylanrenwick** [cyanobacterium/BaseMetals#65]
BM's ores have noticeably higher hardness than Iron (meaning they take longer to mine) even those that logically should be softer (such as copper and tin)

After briefly inspecting BM's source, it appears BlockMetalOre has a _minimum_ hardness of 5.0f, and according to the comments for reference in the MetalMaterial class, Iron is listed as 8 hardness.

Iron Ore's Block hardness is 3.0f
(Source: http://minecraft.gamepedia.com/Iron_Ore)

**Comment by jriwanek** [comment]
Moved to new tracker
