### ISSUE TITLE
Crack Hammer problem

### ISSUE THREAD

**Issue by kley2101** [cyanobacterium/BaseMetals#66]
My minecraft 1.9.4 wont have the recipes for the crack hammer, and i can get only one via creative, and this one makes none (acts like i broking the ore with a sand block, for example).

**Comment by jriwanek** [comment]
What other mods are you using, what version of forge?

**Comment by kley2101** [comment]
Forge 12.17.0.1975
i am using the ore spawn, power advantage, steam advantage, electric advantage and journey map. The hammers work if i remove the power advantage and his add-ons.

**Comment by jriwanek** [comment]
There is no official Forge 12.17.0.1975, there is however 1974 and 1976, I've tested with the modlist you mentioned (and the two versions of forge I mentioned above) and found no issue crafting hammers, check that you're using stone bricks to make the stone crack hammer or a block of metal above two sticks, Mod versions I used:

Base Metals: 1.9.4-2.3.2.6
OreSpawn: 1.9.4-1.0.3
Electric Advantage: 1.9-2.1.0
JourneyMap: 1.9.4-5.2.3-unlimited
Power Advantage: 1.9.4-2.2.1
Steam Advantage: 1.9.4-2.1.0

Let me know if you were using different versions, also try wiping your configs, if that doesn't work try redownloading the various mods.

**Comment by kley2101** [comment]
Thanks, i wiped the configs of these mods and it return to work.
