### ISSUE TITLE
Requesting permission to use StarSteel texture

### ISSUE THREAD

**Issue by dries007** [cyanobacterium/BaseMetals#69]
I would like to request your permission to make a star steel lumberaxe texture and distribute it with my mod Lumberjack, under my own license (MIT), based on one of the original starsteel files. Since it would be a derivative work, I thought it would be best to ask explicit permission.

If you happen to remember which one you used for the axe, I'll use the same one.

Thanks in advance
Dries
See DoubleDoorDevelopment/Lumberjack#9

**Comment by jriwanek** [comment]
Base Metals is Licensed under the LGPL, atleast for code, I'm not sure what license Cyano Decided on for the art however and he's not been around for a while. I can't personally grant permission, but I _suspect_ it would be okay for you to do so aslong as you give credit to @cyanobacterium for the Star-Steel texture.

**Comment by jriwanek** [comment]
@dries007 as per:
https://github.com/cyanobacterium/BaseMetals/issues/79

Permission granted.

**Comment by dries007** [comment]
Thanks!
