### ISSUE TITLE
Base Metals won't spawn even if other ores added to Orespawn do.

### ISSUE THREAD

**Issue by Sukid** [cyanobacterium/BaseMetals#72]
I'm not sure what it is about my mod setup, I've tried disabling so many mods in my pack so far and this still keeps happening. I've even tried forcing orespawn's generation and even telling Base Metals that it's not using orespawn, just to see if that might have any effect on things.  Still none of the Base Metals will generate, even when the Nether and End metals and my own json file's ores do spawn. Yes the nether metals spawning do include the ones that depend on Base Metals.
The Base Metals themselves are indeed present in the game and I can spawn them in creative, look at them in Jei, or find them in loot chests.

I am beyond confused. Are there any known incompatabilities that I'm just missing? Mods I have tried disabling include Biometweaker, Abyssalcraft, ArmorPlus,  Chisel, Biomes o Plenty, Default Options, Simple Dimensions, terraqueous and all of the mods in its core, Better Bedrock Gen, Doomlike Dungeons, and also going to the latest and recommended versions of Forge. It's like something is outright preventing the Base Metal ores from generating.
While not in the best format, this is my modpack's list: http://pastebin.com/Ct8f5YNv

**Comment by Sukid** [comment]
Okay so for one, regenrating all my mods config files seemed to fix it rather than transferring the config files to the forge profile as well. Also, for some reason even on my server which did not regen its config files yet, fixing the base metals' oredidct entries using Crafting Harmonics(which I discovered were messed up due to my experiments with creating crafting recipes with that mod) seemed to fix it. So maybe it's something to do with that? It's just very strange that Base Metals was afflicted with that problem and not the others.

**Comment by jriwanek** [comment]
Did you use any other mods by cyano or myself? it's unlikely that playing with the oredict entries would have affected it at all for reference.

**Comment by mr-poyo** [comment]
Was this ever resolved or figured out? I am having the same exact issue as Sukid with a custom mod-pack I created. Added this pack at the very end since I noticed none of my other mods supply a decent amount of copper ore for EnderIO.

Update: Nevermind. I used the latest 1.x.x orespawn version instead of the alpha 2.x.x version. working now~

**Comment by jriwanek** [comment]
Orespawn 2.0.0.10 and later no longer have the importer, it was very broken, a quick fix if you need to use BMe with OS2, is to start once using OS 2.0.0.9, to generate the new style configs, then update to the latest 2.x release.

**Comment by Sukid** [comment]
Oh, sorry to not follow up but I realized the problem happens whenever I update the modpack. The problem seems to be fixed whenever I delete the config files that _forge_ makes and regenerate them, not the base metals config or anything else.

**Comment by jriwanek** [comment]
What do you mean that forge makes?
names of the files would be helpful.

**Comment by jriwanek** [comment]
No additional information provided after over a month, assuming fixed.
