### ISSUE TITLE
Crack Hammer does not pulverize entire ItemStack

### ISSUE THREAD

**Issue by skyjay1** [cyanobacterium/BaseMetals#73]
Using any Crack Hammer on a dropped ItemStack only pulverizes one ore at a time from the stack.
Personally, I'm OK with this. But some people want to crush the entire stack in one click.

Suggested fix: add config option (disabled by default) for crack hammer to pulverize the entire ItemStack it clicks on. This ability may only trigger while sneaking, if that is desired.

**Comment by jriwanek** [comment]
Moved to new tracker

**Comment by dshadowwolf** [comment]
@sky0-1 Latest commit to the [new repo](http://github.com/MinecraftModDevelopment/BaseMetals) has this feature. Thank you for your patience!
