### ISSUE TITLE
Balancing

### ISSUE THREAD

**Issue by Keridos** [cyanobacterium/BaseMetals#76]
Can you default the Gears produced by the gears to 1? That would make it to be inline with pretty much any other mods gears. Currently the gears from BaseMetals are way cheaper than any of the alternatives.

Also I propose more coal dust need for Steel, also to bring it in line with other mods.

**Comment by jriwanek** [comment]
I can put in a config option for the former, could you provide some examples of the other mods?

**Comment by Keridos** [comment]
Forestry gears are 4 ingots per piece, as well as immersive engineering and gregtech ones. Steel in TechReborn/Gregtech is 2 coal, 1 iron per steel, railcraft is 4 charcoal or 1 coal and 1 iron for one steel ingot.

**Comment by jriwanek** [comment]
Config for gear quantity will be in next release.
