### ISSUE TITLE
Malisis Doors Integration

### ISSUE THREAD

**Issue by brisingraerowing** [cyanobacterium/BaseMetals#78]
I was wondering if you guys could integrate with Malisis Doors to add animations to the doors in Base Metals. 

There's a basic guide at the bottom of the [Official Malisis Doors MCF Post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-malisisdoors-1-9-4-5-0-2-1-9-4-0-2-03-08-2016).

I like the doors added by Base Metals (especially the Star Steel door), but I also like how Malisis Doors adds animations for doors (and fence gates and trapdoors).

I did notice the issue with Malisis Doors, Base Metals, and vanilla door textures.

**Comment by jriwanek** [comment]
I'll take a look into it.

**Comment by jriwanek** [comment]
Moved to new tracker
