### ISSUE TITLE
The future of Base Metals

### ISSUE THREAD

**Issue by jriwanek** [cyanobacterium/BaseMetals#79]
Just a prod to remind you (drcyano) to check your curse inbox about me continuing the work.

**Comment by DrPlantabyte** [comment]
Oh sorry. I haven't read it yet, but you can have free reign over any (or even all) of my mods that you want to change/update. I'm retiring from Minecraft modding. It has been a good couple of years but I'm moving my free time over to other hobbies.

**Comment by jriwanek** [comment]
Yeah, I'd seen that, what I was after was ownership of the CF project pages, mostly so as to avoid multiple different projects confusing the users. details are on the message on curse, but basically if you transfer the git projects too it just makes it all cleaner.

**Comment by DrPlantabyte** [comment]
Ok. Again, sorry for my delays. I'll give you full ownership of it.
