### ISSUE TITLE
Crash on game launch (client)

### ISSUE THREAD

**Issue by Baltic0** [cyanobacterium/BaseMetals#81]
Error:       at cyano.basemetals.BaseMetals.preInit(BaseMetals.java:158)

here the full log http://pastebin.com/f2dvcRV1

**Comment by jriwanek** [comment]
You forgot to install orespawn, get it at:
https://minecraft.curseforge.com/projects/mmd-orespawn

Also, this is not the correct issue tracker, use this one in future:
https://github.com/MinecraftModDevelopment/basemetals
