### ISSUE TITLE
Issue with Thermal Expansion

### ISSUE THREAD

**Issue by Rayzilla68** [cyanobacterium/BaseMetals#89]
I am trying to run this mod with Thermal Expansion, but when I do it keeps throwing the attached error.

[crash-2018-06-11_17.10.33-client.txt](https://github.com/cyanobacterium/BaseMetals/files/2092136/crash-2018-06-11_17.10.33-client.txt)

Thanks.

**Comment by jriwanek** [comment]
Turn off the TE plugin in the basemetals config, that'll solve the problem, it'll be automatic in the next release. also, in future, use the current issue tracker at https://github.com/MinecraftModDevelopmentMods/basemetals/issues this one is obsolete, as stated in the readme on the front page.
