### ISSUE TITLE
Base metals x Sponge forge issue

### ISSUE THREAD

**Issue by Cenbes** [cyanobacterium/BaseMetals#90]
Base Metals refusing to work with sponge forge, bcs it is loading one of its class before sponge can patch it. This mod can´t be used on moded moded servers...
https://pastebin.com/0bicw4Db

**Comment by jriwanek** [comment]
I can't see anything in that log showing BaseMetals being at fault, this is also *not* the correct tracker, BaseMetals moved to https://github.com/MinecraftModDevelopmentMods/BaseMetals a very long time ago, please test again with JUST BaseMetals, and no other mods and if the problem persists, report there.
