### ISSUE TITLE
Crash NumberFormatException: For input string: "0,10"

### ISSUE THREAD

**Issue by JorisBaron** [cyanobacterium/BaseMetals#91]
Hi,
Here is the crash log of my server : 
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Base Metals (basemetals)
Caused by: java.lang.NumberFormatException: For input string: "0,10"
```
My server in hosted in France, so I think it could be a locale problem, but i don't know how I can solve it on my side

[EDIT] Forgot to mention that it was only on `beta6.280` version

**Comment by GhostZero91** [comment]
Also have the same problem but with beta7.311
[crash-2019-03-21_18.13.56-server.txt](https://github.com/cyanobacterium/BaseMetals/files/2993236/crash-2019-03-21_18.13.56-server.txt)

**Comment by jriwanek** [comment]
Update to beta7.311
